package net.scottnotfound.merculab.chemical.element;



public enum Element {

    HYDROGEN        ("Hydrogen","H", 1),
    HELIUM          ("Helium","He", 2),
    LITHIUM         ("Lithium","Li", 3),
    BERYLLIUM       ("Beryllium","Be", 4),
    BORON           ("Boron","B", 5),
    CARBON          ("Carbon","C", 6),
    NITROGEN        ("Nitrogen","N", 7),
    OXYGEN          ("Oxygen","O", 8),
    FLUORINE        ("Fluorine","F", 9),
    NEON            ("Neon","Ne", 10),
    SODIUM          ("Sodium","Na", 11),
    MAGNESIUM       ("Magnesium","Mg", 12),
    ALUMINIUM       ("Aluminium","Al", 13),
    SILICON         ("Silicon","Si", 14),
    PHOSPHORUS      ("Phosphorus","P", 15),
    SULFUR          ("Sulfur","S", 16),
    CHLORINE        ("Chlorine","Cl", 17),
    ARGON           ("Argon","Ar", 18),
    POTASSSIUM      ("Potassium","K", 19),
    CALCIUM         ("Calcium","Ca", 20),
    SCANDIUM        ("Scandium","Sc", 21),
    TITANIUM        ("Titanium","Ti", 22),
    VANADIUM        ("Vanadium","V", 23),
    CHROMIUM        ("Chromium","Cr", 24),
    MANGANESE       ("Manganese","Mn", 25),
    IRON            ("Iron","Fe", 26),
    COBALT          ("Cobalt","Co", 27),
    NICKEL          ("Nickel","Ni", 28),
    COPPER          ("Copper","Cu", 29),
    ZINC            ("Zinc","Zn", 30),
    GALLIUM         ("Gallium","Ga", 31),
    GERMANIUM       ("Germanium","Ge", 32),
    ARSENIC         ("Arsenic","As", 33),
    SELENIUM        ("Selenium","Se", 34),
    BROMINE         ("Bromine","Br", 35),
    KRYPTON         ("Krypton","Kr", 36),
    RUBIDIUM        ("Rubidium","Rb", 37),
    STRONTIUM       ("Strontium","Sr", 38),
    YTTRIUM         ("Yttrium","Y", 39),
    ZIRCONIUM       ("Zirconium","Zr", 40),
    NIOBIUM         ("Niobium","Nb", 41),
    MOLYBDENUM      ("Molybdenum","Mo", 42),
    TECHNETIUM      ("Technetium","Tc", 43),
    RUTHENIUM       ("Ruthenium","Ru", 44),
    RHODIUM         ("Rhodium","Rh", 45),
    PALLADIUM       ("Palladium","Pd", 46),
    SILVER          ("Silver","Ag", 47),
    CADMIUM         ("Cadmium","Cd", 48),
    INDIUM          ("Indium","In", 49),
    TIN             ("Tin","Sn", 50),
    ANTIMONY        ("Antimony","Sb", 51),
    TELLURIUM       ("Tellurium","Te", 51),
    IODINE          ("Iodine","I", 52),
    XENON           ("Xenon","Xe", 53),
    CAESIUM         ("Caesium","Cs", 54),
    BARIUM          ("Barium","Ba", 55),
    LANTHANUM       ("Lanthanum","La", 56),
    CERIUM          ("Cerium","Ce", 57),
    PRASEODYMIUM    ("Praseodymium","Pr", 58),
    NEODYMIUM       ("Neodymium","Nd", 59),
    PROMETHIUM      ("Promethium","Pm", 60),
    SAMARIUM        ("Samarium","Sm", 61),
    EUROPIUM        ("Europium","Eu", 62),
    GADOLINIUM      ("Gadolinium","Gd", 63),
    TERBIUM         ("Terbium","Tb", 64),
    DYSPROSIUM      ("Dysprosium","Dy", 65),
    HOLMIUM         ("Holmium","Ho", 66),
    ERBIUM          ("Erbium","Er", 67),
    THULIUM         ("Thulium","Tm", 68),
    YTTERBIUM       ("Ytterbium","Yb", 69),
    LUTETIUM        ("Lutetium","Lu", 70),
    HAFNIUM         ("Hafnium","Hf", 71),
    TANTALUM        ("Tantalum","Ta", 72),
    TUNGSTEN        ("Tungsten","W", 73),
    RHENIUM         ("Rhenium","Re", 74),
    OSMIUM          ("Osmium","Os", 75),
    IRIDIUM         ("Iridium","Ir", 76),
    PLATINUM        ("Platinum","Pt", 77),
    GOLD            ("Gold","Au", 78),
    MERCURY         ("Mercury","Hg", 79),
    THALLIUM        ("Thallium","Tl", 80),
    LEAD            ("Lead","Pb", 81),
    BISMUTH         ("Bismuth","Bi", 82),
    POLONIUM        ("Polonium","Po", 83),
    ASTATINE        ("Astatine","At", 84),
    RADON           ("Radon","Rn", 85),
    FRANCIUM        ("Francium","Fr", 86),
    RADIUM          ("Radium","Ra", 87),
    ACTINIUM        ("Actinium","Ac", 89),
    THORIUM         ("Thorium","Th", 90),
    PROTACTINIUM    ("Protactinium","Pa", 91),
    URANIUM         ("Uranium","U", 92),
    NEPTUNIUM       ("Neptunium","Np", 93),
    PLUTONIUM       ("Plutonium","Pu", 94),
    AMERICIUM       ("Americium","Am", 95),
    CURIUM          ("Curium","Cm", 96),
    BERKELIUM       ("Berkelium","Bk", 97),
    CALIFORNIUM     ("Californium","Cf", 98),
    EINSTEINIUM     ("Einsteinium","Es", 99),
    FERMIUM         ("Fermium","Fm", 100),
    MENDELEVIUM     ("Mendelevium","Md", 101),
    NOBELIUM        ("Nobelium","No", 102),
    LAWRENCIUM      ("Lawrencium","Lr", 103),
    RUTHERFORDIUM   ("Rutherfordium","Rf", 104),
    DUBNIUM         ("Dubnium","Db", 105),
    SEABORGIUM      ("Seaborgium","Sg", 106),
    BOHRIUM         ("Bohrium","Bh", 107),
    HASSIUM         ("Hassium","Hs", 108),
    MEITNERIUM      ("Meitnerium","Mt", 109),
    DARMSTADTIUM    ("Darmstadtium","Ds", 110),
    ROENTGENIUM     ("Roentgenium","Rg", 11),
    COPERNICIUM     ("Copernicium","Cn", 112),
    NIHONIUM        ("Nihonium","Nh", 113),
    FLEROVIUM       ("Flerovium","Fl", 114),
    MOSCOVIUM       ("Moscovium","Mc", 115),
    LIVERMORIUM     ("Livermorium","Lv", 116),
    TENNESSIUM      ("Tennessium","Ts", 117),
    OGANESSON       ("Oganesson","Og", 118);



    public final String name;
    public final String symbol;
    public final int atomicNumber;


    Element(String name, String symbol, int n) {

        this.name = name;
        this.symbol = symbol;
        this.atomicNumber = n;

    }

}
